services:
  backend:
    build:
      context: ./backend
    container_name: mall-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    networks:
      - mall-network

  frontend:
    build:
      context: ./store-dashboard
    container_name: mall-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://mall-backend:5000/event
    networks:
      - mall-network
    depends_on:
      - backend

networks:
  mall-network:
